name: Python Application Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Script
      run: python utils.py

    - name: Use a Secret
      run: |
        echo "My secret is $MY_SECRET"
      env:
        MY_SECRET: ${{ secrets.OPENAI }}
